# Generated by Django 4.2 on 2023-07-25 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Winter', 'Winter')], max_length=10)),
                ('program', models.CharField(choices=[('Bachelors/BS', 'Bachelors/BS'), ('MS/M.phil', 'MS/M.phil'), ('Phd', 'Phd')], max_length=15)),
                ('admission_test', models.CharField(choices=[('Not required', 'Not required'), ('NTS NAT', 'NTS NAT'), ('ECAT', 'ECAT'), ('MCAT', 'MCAT')], max_length=20)),
                ('no_of_shortlisted_students', models.IntegerField()),
                ('intermediate_required_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bachelor_required_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test_required_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('departments', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StdInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('cnic', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('intermediate', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=100)),
                ('college_graduation_date', models.DateField()),
                ('inter_obtained_marks', models.PositiveIntegerField(null=True)),
                ('inter_total_marks', models.PositiveIntegerField(null=True)),
                ('matriculation', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('matric_graduation_date', models.DateField()),
                ('matric_obtained_marks', models.PositiveIntegerField(null=True)),
                ('matric_total_marks', models.PositiveIntegerField(null=True)),
                ('self_photo', models.ImageField(upload_to='student/')),
                ('id_card_photo', models.ImageField(upload_to='student/')),
                ('inter_transcript', models.FileField(upload_to='student/')),
                ('inter_degree', models.FileField(upload_to='student/')),
                ('matric_transcript', models.FileField(upload_to='student/')),
                ('matric_degree', models.FileField(upload_to='student/')),
            ],
        ),
        migrations.CreateModel(
            name='UniInfoTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('hec_registration_number', models.CharField(max_length=15)),
                ('hec_recognized', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
