# Generated by Django 4.2 on 2023-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='campus',
            field=models.CharField(default=True, max_length=300),
        ),
    ]
