# Generated by Django 4.2 on 2023-07-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psapApp', '0003_appliedforadmissionform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedForAdmissionForm',
        ),
    ]
